export enum ActionType {
  ADD_SITE_TO_PINNED_SITES = 'ADD_SITE_TO_PINNED_SITES',
  MOVE_PINNED_SITE_TO_TOP_SITES = 'MOVE_PINNED_SITE_TO_TOP_SITES',
  MOVE_TOP_SITE_TO_PINNED_SITES = 'MOVE_TOP_SITE_TO_PINNED_SITES',
  REMOVE_SITE_FROM_PINNED_SITES = 'REMOVE_SITE_FROM_PINNED_SITES',
  SET_DIFFERENCE_TO_TOP_SITES = 'SET_DIFFERENCE_TO_TOP_SITES',
  SET_TOP_SITES = 'SET_TOP_SITES',
}
