export enum ActionType {
  ADD_SITE_TO_PINNED_SITES = 'ADD_SITE_TO_PINNED_SITES',
  MOVE_SITE_FROM_TOP_SITES_TO_PINNED_SITES = 'MOVE_SITE_FROM_TOP_SITES_TO_PINNED_SITES',
  REMOVE_SITE_FROM_TOP_SITES = 'REMOVE_SITE_FROM_TOP_SITES',
  SET_TOP_SITES = 'SET_TOP_SITES',
}
